### PR TITLE
Proxy configuration support in TestLinkHelper

### PR DESCRIPTION
**Pull request by Maberi**
This patch allows easy proxy configuration using TestLinkHelper.

Adds a new --proxy option in command line.
Recognizes "http_proxy" environment variable.

### CODE REVIEW

**Comment by lczub** [comment]
Hello Mario,

FYI, with 3b8fae8 your ProxiedTransport should now be usable under py3

regards, Luiko

**Comment by Maberi** [comment]
Thank you, Luiko!

**Comment by hellboy81** [comment]
I am trying to use proxy setting in constructor:

```python
tls = testlink.TestLinkHelper(
    TESTLINK_API_PYTHON_SERVER_URL,
    TESTLINK_API_PYTHON_DEVKEY,
    TESTLINK_API_PYTHON_PROXY,
).connect(testlink.TestlinkAPIClient)

projectsCount = tls.countProjects()
```

Got exception:

```python
Traceback (most recent call last):
  File "C:/../TestLink-API-Python-client-test/test.py", line 15, in <module>
    tls.countProjects()
  File "C:\...\TestLink-API-Python-client-test\venv\lib\site-packages\testlink\testlinkapi.py", line 392, in countProjects
    projects=self.getProjects()
  File "C:\...\TestLink-API-Python-client-test\venv\lib\site-packages\testlink\testlinkdecorators.py", line 140, in wrapperReplaceTLResponseError
    response = methodAPI(self, *argsPositional, **argsOptional)
  File "C:\...\TestLink-API-Python-client-test\venv\lib\site-packages\testlink\testlinkdecorators.py", line 112, in wrapperAddDevKey
    return methodAPI(self, *argsPositional, **argsOptional)
  File "C:\...\TestLink-API-Python-client-test\venv\lib\site-packages\testlink\testlinkdecorators.py", line 99, in wrapperWithArgs
    return self.callServerWithPosArgs(methodAPI.__name__, 
  File "C:\...\TestLink-API-Python-client-test\venv\lib\site-packages\testlink\testlinkapigeneric.py", line 1582, in callServerWithPosArgs
    response = self._callServer(methodNameAPI, argsOptional)
  File "C:\...\TestLink-API-Python-client-test\venv\lib\site-packages\testlink\testlinkapigeneric.py", line 2057, in _callServer
    response = getattr(self.server.tl, methodNameAPI)(argsAPI)
  File "C:\Python\lib\xmlrpc\client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "C:\Python\lib\xmlrpc\client.py", line 1450, in __request
    response = self.__transport.request(
  File "C:\Python\lib\xmlrpc\client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Python\lib\xmlrpc\client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
TypeError: send_request() takes 4 positional arguments but 5 were given
```

**Comment by lczub** [comment]
Hello hellboy881,

I guess your report is a duplicate of #127.
Try the suggested workaround https://github.com/lczub/TestLink-API-Python-client/issues/127#issuecomment-613473372.
Please add further comments on #127.

I will try to find a solution during the next weeks

regards Luiko

**Pull request closed without merging**
